import type { Locale } from "@/i18n/config";

export const projectSiteCopy = {
  en: {
    auth: {
      heading: "Sign in",
      description: "Sign in to your account to continue",
      continueWithGoogle: "Continue with Google",
      signingIn: "Signing in...",
      errorOAuth: "Sign in failed. Please try again.",
      errorConfig: "Google sign-in is not configured for this project.",
    },
    dashboard: {
      title: "Dashboard",
      home: {
        overview: "Overview",
        welcome: "Welcome back, {name}",
      },
      widgets: {
        empty: "No active widgets.",
        customize: "Customize widgets",
        expand: "Expand",
        collapse: "Collapse",
        domainStatus: {
          name: "Domain status",
          eyebrow: "Project domain",
          currentTemporary: "Running on the Infologist temporary domain",
          currentCustom: "Running on its own domain",
          projectActive: "Project active",
          projectInactive: "Project inactive",
          temporaryTitle: "Infologist temporary domain",
          temporaryDescription: "Always available while the project is active.",
          customTitle: "Own domain",
          customEmpty: "No own domain has been connected yet.",
          customVerified: "DNS is verified and ready.",
          customPending: "DNS is connected but waiting for verification.",
          active: "Active",
          inactive: "Inactive",
          pending: "Pending",
          current: "This is the domain serving the current dashboard session.",
        },
        mediaUsage: {
          name: "Media usage",
          eyebrow: "Project storage",
          used: "Used",
          free: "Free",
          total: "Total",
          megabytes: "MB",
          gigabytes: "GB",
        },
        statisticsAnalytics: {
          name: "Analytics",
          uniqueSessions: "Sessions",
          uniqueVisitors: "Unique Visitors",
          avgSessionDuration: "Avg session",
          minUnit: "min",
          liveUsers: "Live users",
          noData: "No data yet",
          refresh: "Refresh",
        },
        modulesPage: {
          title: "Features",
          description: "Manage available features and their settings.",
          noData: "No features available",
          settingsLabel: "Settings",
          searchPlaceholder: "Search features...",
          status: {
            active: "Active",
            inactive: "Inactive",
          },
          columns: {
            name: "Name",
            description: "Description",
            type: "Type",
            version: "Version",
            actions: "Actions",
          },
          types: {
            core: "Core",
            site: "Site",
            admin: "Admin",
          },
          exportModule: "Export",
          exportFailed: "Export failed",
          exportTooltip:
            "Export module as ZIP (includes code + data snapshot, for moving between installations)",
          dataTooltip: "Export & import module data",
          importModule: "Import",
          importTooltip: "Import module from ZIP",
          importLoading: "Uploading module...",
          importProcessing: "Processing...",
          importDone: "Feature imported successfully",
          importFailed: "Import failed",
          importInvalidFile: "Please select a valid .zip file",
          deleteModule: "Delete",
          deleteConfirmTitle: 'Delete "{name}"?',
          deleteConfirmDescription:
            "This will permanently remove the module and all its data from disk. This action cannot be undone.",
          deleteConfirmAction: "Yes, delete",
          deleteCancel: "Cancel",
          deleteLoading: "Deleting feature...",
          deleteSuccess: 'Feature "{name}" removed',
          deleteFailed: "Delete failed",
          statusUpdated: "Module status updated",
          statusUpdateFailed: "Failed to update module status",
          settings: {
            title: "{moduleName} – Settings",
            description:
              "Configure navigation, access roles, and display options for this feature.",
            notFound: "Feature not found",
            failedToLoad: "Failed to load feature settings",
            updateSuccess: "Settings saved",
            updateFailed: "Failed to save settings",
            saveConfig: "Save",
            tabSettings: "Settings",
            tabNavigation: "Navigation",
            tabElements: "Elements",
            menuSectionTitle: "Navigation Menu",
            menuConfigDescription:
              "Configure which pages appear in the sidebar and who can access them.",
            noPages: "This feature has no configurable pages.",
            menuName: "Page",
            urlPath: "URL",
            icon: "Icon",
            accessFor: "Access for",
            mainIcon: "Feature Icon",
            displayConfigTitle: "Dashboard Elements",
            dashboardWidgets: "Widgets",
            frontendComponents: "Frontend Components",
            enableWidget: "Show in dashboard",
            enableFrontend: "Enabled",
            previewComp: "Preview: {component}",
            copiedToClipboard: "Copied to clipboard",
            customSettingsTitle: "Feature Settings",
          },
        },
      },
    },
    navigation: {
      dashboard: "Dashboard",
      statistics: "Statistics",
      media: "Media",
      mediaLibrary: "Library",
      mediaUpload: "Add media",
      aiAssistant: "AI Assistant",
      management: "Management",
      pageBuilder: "Page Builder",
      promptTemplates: "Prompt templates",
      modules: "Modules",
      profile: "Profile",
      settings: "Settings",
    },
    statistics: {
      title: "Statistics",
      description: "Visitor analytics for your project site.",
      analytics: "Analytics",
      visitors: "Visitors",
      live: "Live",
      search: "Search visitors",
      uniqueVisitors: "Unique Visitors",
      sessions: "Sessions",
      totalActiveMin: "Total Active (min)",
      avgActiveMin: "Avg Active (min)",
      topPages: "Top Pages",
      os: "OS",
      browsers: "Browsers",
      referrals: "Referrals",
      liveUsers: "Live users",
      visitorId: "Visitor ID",
      userId: "User ID",
      ip: "IP",
      entry: "Entry",
      activeMin: "Active (min)",
      path: "Path",
      lastSeen: "Last seen",
      noData: "No data yet",
      refresh: "Refresh",
      previous: "Previous",
      next: "Next",
      error: "Failed to load analytics",
    },
    common: {
      openMenu: "Open menu",
      closeMenu: "Close menu",
      signOut: "Sign out",
    },
  },
  fa: {
    auth: {
      heading: "ورود",
      description: "برای ادامه وارد حساب کاربری خود شوید",
      continueWithGoogle: "ادامه با گوگل",
      signingIn: "در حال ورود...",
      errorOAuth: "ورود ناموفق بود. دوباره تلاش کنید.",
      errorConfig: "ورود با گوگل برای این پروژه پیکربندی نشده است.",
    },
    dashboard: {
      title: "داشبورد",
      home: {
        overview: "نمای کلی",
        welcome: "خوش آمدید، {name}",
      },
      widgets: {
        empty: "ویجت فعالی وجود ندارد.",
        customize: "سفارشی‌سازی ویجت‌ها",
        expand: "گسترش",
        collapse: "جمع کردن",
        domainStatus: {
          name: "وضعیت دامنه",
          eyebrow: "دامنه پروژه",
          currentTemporary: "روی دامنه موقت Infologist اجرا می‌شود",
          currentCustom: "روی دامنه اختصاصی خودش اجرا می‌شود",
          projectActive: "پروژه فعال",
          projectInactive: "پروژه غیرفعال",
          temporaryTitle: "دامنه موقت Infologist",
          temporaryDescription: "تا وقتی پروژه فعال باشد همیشه در دسترس است.",
          customTitle: "دامنه اختصاصی",
          customEmpty: "هنوز دامنه اختصاصی وصل نشده است.",
          customVerified: "DNS تایید شده و آماده است.",
          customPending: "DNS وصل شده اما منتظر تایید است.",
          active: "فعال",
          inactive: "غیرفعال",
          pending: "در انتظار",
          current: "این دامنه همین نشست داشبورد را سرو می‌کند.",
        },
        mediaUsage: {
          name: "مصرف رسانه",
          eyebrow: "فضای پروژه",
          used: "مصرف‌شده",
          free: "آزاد",
          total: "کل",
          megabytes: "مگابایت",
          gigabytes: "گیگابایت",
        },
        statisticsAnalytics: {
          name: "آنالیتیکس",
          uniqueSessions: "نشست‌ها",
          uniqueVisitors: "بازدیدکنندگان منحصربه‌فرد",
          avgSessionDuration: "میانگین نشست",
          minUnit: "دقیقه",
          liveUsers: "کاربران آنلاین",
          noData: "هنوز داده‌ای وجود ندارد",
          refresh: "بارگذاری مجدد",
        },
        modules: {
          name: "ماژول‌ها",
          empty: "هنوز ماژولی نصب نشده.",
          open: "باز کردن",
        },
        modulesPage: {
          title: "قابلیت‌ها",
          description: "مدیریت قابلیت‌های در دسترس و تنظیمات آن‌ها.",
          noData: "هیچ قابلیتی در دسترس نیست",
          settingsLabel: "تنظیمات",
          searchPlaceholder: "جستجوی قابلیت...",
          status: {
            active: "فعال",
            inactive: "غیرفعال",
          },
          columns: {
            name: "نام",
            description: "توضیحات",
            type: "نوع",
            version: "نسخه",
            actions: "عملیات",
          },
          types: {
            core: "هسته",
            site: "سایت",
            admin: "ادمین",
          },
          exportModule: "خروجی",
          exportFailed: "خطا در خروجی گرفتن",
          exportTooltip:
            "خروجی ماژول به صورت ZIP (شامل کد + اسنپ‌شات داده، برای انتقال بین سرورها)",
          dataTooltip: "خروجی و ورود داده‌های ماژول",
          importModule: "وارد کردن",
          importTooltip: "وارد کردن ماژول از ZIP",
          importLoading: "در حال آپلود ماژول...",
          importProcessing: "در حال پردازش...",
          importDone: "قابلیت با موفقیت وارد شد",
          importFailed: "خطا در وارد کردن",
          importInvalidFile: "لطفاً یک فایل .zip معتبر انتخاب کنید",
          deleteModule: "حذف",
          deleteConfirmTitle: 'حذف "{name}"؟',
          deleteConfirmDescription:
            "این ماژول و تمام داده‌هایش به‌طور دائمی از دیسک حذف می‌شود. این عمل قابل بازگشت نیست.",
          deleteConfirmAction: "بله، حذف کن",
          deleteCancel: "انصراف",
          deleteLoading: "در حال حذف قابلیت...",
          deleteSuccess: 'قابلیت "{name}" حذف شد',
          deleteFailed: "خطا در حذف",
          statusUpdated: "وضعیت ماژول به‌روز شد",
          statusUpdateFailed: "خطا در به‌روزرسانی وضعیت",
          settings: {
            title: "{moduleName} – تنظیمات",
            description:
              "پیکربندی ناوبری، نقش‌های دسترسی و گزینه‌های نمایش برای این قابلیت.",
            notFound: "قابلیت پیدا نشد",
            failedToLoad: "خطا در بارگذاری تنظیمات قابلیت",
            updateSuccess: "تنظیمات ذخیره شد",
            updateFailed: "خطا در ذخیره تنظیمات",
            saveConfig: "ذخیره",
            tabSettings: "تنظیمات",
            tabNavigation: "ناوبری",
            tabElements: "المان‌ها",
            menuSectionTitle: "منوی ناوبری",
            menuConfigDescription:
              "تنظیم صفحاتی که در سایدبار نمایش داده می‌شوند.",
            noPages: "این قابلیت هیچ صفحه قابل تنظیمی ندارد.",
            menuName: "صفحه",
            urlPath: "آدرس",
            icon: "آیکون",
            accessFor: "دسترسی برای",
            mainIcon: "آیکون قابلیت",
            displayConfigTitle: "المان‌های داشبورد",
            dashboardWidgets: "ویجت‌ها",
            frontendComponents: "کامپوننت‌های فرانت‌اند",
            enableWidget: "نمایش در داشبورد",
            enableFrontend: "فعال",
            previewComp: "پیش‌نمایش: {component}",
            copiedToClipboard: "کپی شد",
            customSettingsTitle: "تنظیمات قابلیت",
          },
        },
      },
    },
    navigation: {
      dashboard: "داشبورد",
      statistics: "آمار",
      media: "رسانه",
      mediaLibrary: "کتابخانه",
      mediaUpload: "افزودن رسانه",
      aiAssistant: "دستیار هوش مصنوعی",
      management: "مدیریت",
      pageBuilder: "سازنده صفحات",
      promptTemplates: "قالب‌های پرامپت",
      modules: "ماژول‌ها",
      profile: "پروفایل",
      settings: "تنظیمات",
    },
    statistics: {
      title: "آمار",
      description: "آنالیتیکس بازدیدکنندگان سایت پروژه.",
      analytics: "آنالیتیکس",
      visitors: "بازدیدکنندگان",
      live: "زنده",
      search: "جست‌وجوی بازدیدکنندگان",
      uniqueVisitors: "بازدیدکنندگان منحصربه‌فرد",
      sessions: "نشست‌ها",
      totalActiveMin: "مجموع زمان فعال (دقیقه)",
      avgActiveMin: "میانگین زمان فعال (دقیقه)",
      topPages: "صفحات برتر",
      os: "سیستم‌عامل",
      browsers: "مرورگرها",
      referrals: "منابع ارجاع",
      liveUsers: "کاربران آنلاین",
      visitorId: "شناسه بازدیدکننده",
      userId: "شناسه کاربر",
      ip: "IP",
      entry: "ورود",
      activeMin: "فعال (دقیقه)",
      path: "مسیر",
      lastSeen: "آخرین بازدید",
      noData: "هنوز داده‌ای وجود ندارد",
      refresh: "بارگذاری مجدد",
      previous: "قبلی",
      next: "بعدی",
      error: "بارگذاری آنالیتیکس ناموفق بود",
    },
    common: {
      openMenu: "باز کردن منو",
      closeMenu: "بستن منو",
      signOut: "خروج",
    },
  },
  de: {
    auth: {
      heading: "Anmelden",
      description: "Melden Sie sich an, um fortzufahren",
      continueWithGoogle: "Mit Google fortfahren",
      signingIn: "Anmeldung laeuft...",
      errorOAuth: "Anmeldung fehlgeschlagen. Bitte erneut versuchen.",
      errorConfig:
        "Google-Anmeldung ist fuer dieses Projekt nicht konfiguriert.",
    },
    dashboard: {
      title: "Dashboard",
      home: {
        overview: "Übersicht",
        welcome: "Willkommen zurück, {name}",
      },
      widgets: {
        empty: "Keine aktiven Widgets.",
        customize: "Widgets anpassen",
        expand: "Erweitern",
        collapse: "Verkleinern",
        domainStatus: {
          name: "Domainstatus",
          eyebrow: "Projektdomain",
          currentTemporary: "Laeuft auf der temporaeren Infologist-Domain",
          currentCustom: "Laeuft auf der eigenen Domain",
          projectActive: "Projekt aktiv",
          projectInactive: "Projekt inaktiv",
          temporaryTitle: "Temporaere Infologist-Domain",
          temporaryDescription:
            "Immer verfuegbar, solange das Projekt aktiv ist.",
          customTitle: "Eigene Domain",
          customEmpty: "Noch keine eigene Domain verbunden.",
          customVerified: "DNS ist verifiziert und bereit.",
          customPending: "DNS ist verbunden und wartet auf Verifizierung.",
          active: "Aktiv",
          inactive: "Inaktiv",
          pending: "Ausstehend",
          current: "Diese Domain bedient die aktuelle Dashboard-Sitzung.",
        },
        mediaUsage: {
          name: "Mediennutzung",
          eyebrow: "Projektspeicher",
          used: "Belegt",
          free: "Frei",
          total: "Gesamt",
          megabytes: "MB",
          gigabytes: "GB",
        },
        statisticsAnalytics: {
          name: "Analytik",
          uniqueSessions: "Sitzungen",
          uniqueVisitors: "Eindeutige Besucher",
          avgSessionDuration: "Durchschn. Sitzung",
          minUnit: "Min.",
          liveUsers: "Live-Nutzer",
          noData: "Noch keine Daten",
          refresh: "Aktualisieren",
        },
        modules: {
          name: "Module",
          empty: "Noch keine Module installiert.",
          open: "Öffnen",
        },
        modulesPage: {
          title: "Funktionen",
          description:
            "Verfuegbare Funktionen und ihre Einstellungen verwalten.",
          noData: "Keine Funktionen verfuegbar",
          settingsLabel: "Einstellungen",
          searchPlaceholder: "Funktionen suchen...",
          status: {
            active: "Aktiv",
            inactive: "Inaktiv",
          },
          columns: {
            name: "Name",
            description: "Beschreibung",
            type: "Typ",
            version: "Version",
            actions: "Aktionen",
          },
          types: {
            core: "Kern",
            site: "Website",
            admin: "Admin",
          },
          exportModule: "Exportieren",
          exportFailed: "Export fehlgeschlagen",
          exportTooltip:
            "Modul als ZIP exportieren (inkl. Code + Daten-Snapshot, zum Übertragen zwischen Installationen)",
          dataTooltip: "Moduldaten exportieren & importieren",
          importModule: "Importieren",
          importTooltip: "Modul aus ZIP importieren",
          importLoading: "Modul wird hochgeladen...",
          importProcessing: "Verarbeitung...",
          importDone: "Funktion erfolgreich importiert",
          importFailed: "Import fehlgeschlagen",
          importInvalidFile: "Bitte eine gültige .zip-Datei auswählen",
          deleteModule: "Löschen",
          deleteConfirmTitle: '"{name}" löschen?',
          deleteConfirmDescription:
            "Dieses Modul und alle zugehörigen Daten werden dauerhaft von der Festplatte gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
          deleteConfirmAction: "Ja, löschen",
          deleteCancel: "Abbrechen",
          deleteLoading: "Funktion wird geloescht...",
          deleteSuccess: 'Funktion "{name}" entfernt',
          deleteFailed: "Löschen fehlgeschlagen",
          statusUpdated: "Modulstatus aktualisiert",
          statusUpdateFailed: "Status konnte nicht aktualisiert werden",
          settings: {
            title: "{moduleName} – Einstellungen",
            description:
              "Navigation, Zugriffsrollen und Anzeigeoptionen fuer diese Funktion konfigurieren.",
            notFound: "Funktion nicht gefunden",
            failedToLoad: "Funktionseinstellungen konnten nicht geladen werden",
            updateSuccess: "Einstellungen gespeichert",
            updateFailed: "Einstellungen konnten nicht gespeichert werden",
            saveConfig: "Speichern",
            tabSettings: "Einstellungen",
            tabNavigation: "Navigation",
            tabElements: "Elemente",
            menuSectionTitle: "Navigationsmenü",
            menuConfigDescription:
              "Seiten konfigurieren, die in der Seitenleiste angezeigt werden.",
            noPages: "Diese Funktion hat keine konfigurierbaren Seiten.",
            menuName: "Seite",
            urlPath: "URL",
            icon: "Symbol",
            accessFor: "Zugriff für",
            mainIcon: "Funktionssymbol",
            displayConfigTitle: "Dashboard-Elemente",
            dashboardWidgets: "Widgets",
            frontendComponents: "Frontend-Komponenten",
            enableWidget: "Im Dashboard anzeigen",
            enableFrontend: "Aktiviert",
            previewComp: "Vorschau: {component}",
            copiedToClipboard: "Kopiert",
            customSettingsTitle: "Funktionseinstellungen",
          },
        },
      },
    },
    navigation: {
      dashboard: "Dashboard",
      statistics: "Statistiken",
      media: "Medien",
      mediaLibrary: "Bibliothek",
      mediaUpload: "Medium hinzufügen",
      aiAssistant: "KI-Assistent",
      management: "Verwaltung",
      pageBuilder: "Page Builder",
      promptTemplates: "Prompt-Vorlagen",
      modules: "Module",
      profile: "Profil",
      settings: "Einstellungen",
    },
    statistics: {
      title: "Statistiken",
      description: "Besucheranalysen fuer Ihre Projektseite.",
      analytics: "Analytik",
      visitors: "Besucher",
      live: "Live",
      search: "Besucher suchen",
      uniqueVisitors: "Eindeutige Besucher",
      sessions: "Sitzungen",
      totalActiveMin: "Gesamtaktivzeit (Min.)",
      avgActiveMin: "Durchschn. Aktivzeit (Min.)",
      topPages: "Top-Seiten",
      os: "Betriebssystem",
      browsers: "Browser",
      referrals: "Verweise",
      liveUsers: "Live-Nutzer",
      visitorId: "Besucher-ID",
      userId: "Nutzer-ID",
      ip: "IP",
      entry: "Einstieg",
      activeMin: "Aktiv (Min.)",
      path: "Pfad",
      lastSeen: "Zuletzt gesehen",
      noData: "Noch keine Daten",
      refresh: "Aktualisieren",
      previous: "Zurueck",
      next: "Weiter",
      error: "Analytik konnte nicht geladen werden",
    },
    common: {
      openMenu: "Menue oeffnen",
      closeMenu: "Menue schliessen",
      signOut: "Abmelden",
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;
